title: "Harry Chopra (@harrychopra)"
description: Product designer and web developer at GitHub

author:
  name: Harry Chopra
  handle: harrychopra
  email: coby@cobyism.com

permalink: /blog/:title/
baseurl: /
url: http://harrychopra.github.io
highlighter: rouge

markdown: kramdown
redcarpet:
  extensions: [with_toc_data, footnotes]

sass:
  sass_dir: public/css

exclude: [vendor]

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

google_analytics_id: UA-31312255-4
gauges_id: 50ed90bdf5a1f50492000007
