title: "Coby Chapple (@cobyism)"
description: Product designer and web developer at GitHub

author:
  name: Coby Chapple
  handle: cobyism
  email: coby@cobyism.com

permalink: /blog/:title/
baseurl: /
url: http://cobyism.com
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

google_analytics_id: UA-31312255-4
gauges_id: 50ed90bdf5a1f50492000007
